### PR TITLE
Reorder check logic

### PR DESCRIPTION
**Pull request by lizmat**
* Make 18% faster
* Reorder the checking logic and using a for loop instead of a C-loop
* Use Raku file extensions
* Bump version

### CODE REVIEW

**Comment by lizmat** [comment]
mergeable now

**Comment by lizmat** [comment]
@jnthn something wrong with this PR ?  :-)

**Comment by jnthn** [comment]
Yes, I think the `loop` -> `for` switch has changed the semantics. The `++$I` that requires the `is copy` was meant to affect the index of the iteration, but no longer does.

**Comment by lizmat** [comment]
Changed `for` to `while`, restoring original semantics.  Now at 12% faster.

**Comment by jnthn** [comment]
Curious, is the `while` faster than the original loop? Think it's correct again now, though.

**Comment by lizmat** [comment]
The C-style loop is marginally faster.  (test runs with `while` always end up at .97 seconds for me, with `loop` about half the time it winds up at .96 seconds).
````
$ time raku -e 'use lib "."; use Data::TextOrBinary; my $s := "README.md".IO.open.read; is-text($s) for ^1000'

**Review by jnthn — APPROVED** [review]

**Comment by jnthn** [comment]
Thanks, it's in!

**Comment by lizmat** [comment]
Thanks.

BTW, I checked the use of ternaries, but no difference there.

I also was thinking calculating a max number of unprintables (I guess `$limit +> 7`) and returning `False` as soon as that is exceeded.  But that wouldn't help for pure text files anyway.  And by the time we would reach a maximum number of printables, we'd be close to the end anyway, so the extra check would probably drown-out any improvements.

So I'm now going to use it in App::Rak :-)

**Pull request merged**
